version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'currency_ops'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - db-volume:/var/lib/mysql

  app:
    build:
      context: ../app
      target: release
    depends_on:
      - db
    restart: always
    ports:
      - '8000:8000'

volumes:
  db-volume:
