---
- hosts: target
  gather_facts: no
  become: yes
  tasks:
  - name: Copy src
    copy:
      src: '../{{ item }}/'
      dest: '/opt/sovcom/{{ item }}'
    loop:
      - 'app'
      - 'cicd'

  - name: Install docker module
    pip:
      name: [docker, docker-compose]

  - name: Build new image
    docker_compose:
      project_src: /opt/sovcom/cicd
      state: present
      build: yes
    environment:
      MYSQL_ROOT_PASSWORD: '{{ MYSQL_ROOT_PASSWORD }}'
    register: output

  - name: Restart
    docker_compose:
      project_src: /opt/sovcom/cicd
      services:
        - app
      state: present
      restarted: true
    environment:
      MYSQL_ROOT_PASSWORD: '{{ MYSQL_ROOT_PASSWORD }}'
    register: output

  - debug:
      var: output
