---
- hosts: target
  gather_facts: no
  become: yes
  tasks:
  - name: Copy src
    copy:
      src: '../{{ item }}/'
      dest: '/opt/sovcom/{{ item }}'
    loop:
      - 'app'
      - 'cicd'
    tags: always

  - name: Install docker module
    pip:
      name: [docker, docker-compose]

  - name: Build new image
    docker_compose:
      project_src: /opt/sovcom/cicd
      state: present
      build: yes
    register: output

  - debug:
      var: output

  - name: Restart
    docker_compose:
      project_src: /opt/sovcom/cicd
      services:
        - app
      state: present
      restarted: true
    register: output

  - debug:
      var: output

  - name: Run kafka
    docker_compose:
      project_src: /opt/sovcom/cicd
      files: [docker-compose.kafka.yml]
      state: present
      build: yes
    register: output
    tags: kafka

  - debug:
      var: output
